# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Shopify Plus Scripts
tagline:             'A Repo of Shopify Scripts'
description:         'A repository of example Shopify Plus Scripts.'
url:                 http://shopifyscripts.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Matt Bahr
  url:               https://twitter.com/mattrbahr 
  email:             mattrbahr@gmail.com

# Custom vars
version:             1.0.0
